services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi
  
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
  
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ny_taxi"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8181:80"
    